return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "bash",
        "html",
        "javascript",
        "json",
        "lua",
        "markdown",
        "markdown_inline",
        "python",
        "query",
        "regex",
        "tsx",
        "typescript",
        "vim",
        "yaml",
        "rust",
        "c_sharp",
        "wgsl",
        "c",
        "cpp",
        "cuda",
        "glsl",
        "haskell",
        "hlsl",
        "make",
        "cmake",
        "xml",
        "toml",
        "powershell",
      },
    },
  },
}
